// This file is generated by kconfig_compiler from kobbysettings.kcfg.
// All changes you do to this file will be lost.

#include "kobbysettings.h"

#include <kglobal.h>
#include <QtCore/QFile>

using namespace Kobby;

namespace Kobby {
class KobbySettingsHelper
{
  public:
    KobbySettingsHelper() : q(0) {}
    ~KobbySettingsHelper() { delete q; }
    KobbySettings *q;
};
}
K_GLOBAL_STATIC(KobbySettingsHelper, s_globalKobbySettings)
KobbySettings *KobbySettings::self()
{
  if (!s_globalKobbySettings->q) {
    new KobbySettings;
    s_globalKobbySettings->q->readConfig();
  }

  return s_globalKobbySettings->q;
}

KobbySettings::KobbySettings(  )
  : KConfigSkeleton( QLatin1String( "kobbyrc" ) )
{
  Q_ASSERT(!s_globalKobbySettings->q);
  s_globalKobbySettings->q = this;
  setCurrentGroup( QLatin1String( "ui" ) );

  QList<int> defaultMainWindowGeometry;

  KConfigSkeleton::ItemIntList  *itemMainWindowGeometry;
  itemMainWindowGeometry = new KConfigSkeleton::ItemIntList( currentGroup(), QLatin1String( "MainWindowGeometry" ), mMainWindowGeometry, defaultMainWindowGeometry );
  addItem( itemMainWindowGeometry, QLatin1String( "MainWindowGeometry" ) );
  QList<int> defaultMainWindowHorizSplitterSizes;

  KConfigSkeleton::ItemIntList  *itemMainWindowHorizSplitterSizes;
  itemMainWindowHorizSplitterSizes = new KConfigSkeleton::ItemIntList( currentGroup(), QLatin1String( "MainWindowHorizSplitterSizes" ), mMainWindowHorizSplitterSizes, defaultMainWindowHorizSplitterSizes );
  addItem( itemMainWindowHorizSplitterSizes, QLatin1String( "MainWindowHorizSplitterSizes" ) );

  setCurrentGroup( QLatin1String( "profile" ) );

  KConfigSkeleton::ItemString  *itemNickName;
  itemNickName = new KConfigSkeleton::ItemString( currentGroup(), QLatin1String( "NickName" ), mNickName, QLatin1String( "JohnDoe" ) );
  addItem( itemNickName, QLatin1String( "NickName" ) );
  KConfigSkeleton::ItemColor  *itemUserColor;
  itemUserColor = new KConfigSkeleton::ItemColor( currentGroup(), QLatin1String( "UserColor" ), mUserColor );
  addItem( itemUserColor, QLatin1String( "UserColor" ) );
}

KobbySettings::~KobbySettings()
{
  if (!s_globalKobbySettings.isDestroyed()) {
    s_globalKobbySettings->q = 0;
  }
}

