// This file is generated by kconfig_compiler from kobbysettings.kcfg.
// All changes you do to this file will be lost.
#ifndef KOBBY_KOBBYSETTINGS_H
#define KOBBY_KOBBYSETTINGS_H

#include <kconfigskeleton.h>
#include <kdebug.h>

namespace Kobby {

class KobbySettings : public KConfigSkeleton
{
  public:

    static KobbySettings *self();
    ~KobbySettings();

    /**
      Set Main Window location and size.
    */
    static
    void setMainWindowGeometry( const QList<int> & v )
    {
      if (!self()->isImmutable( QString::fromLatin1 ( "MainWindowGeometry" ) ))
        self()->mMainWindowGeometry = v;
    }

    /**
      Get Main Window location and size.
    */
    static
    QList<int> mainWindowGeometry()
    {
      return self()->mMainWindowGeometry;
    }

    /**
      Set Sizes of main splitter.
    */
    static
    void setMainWindowSplitterSizes( const QList<int> & v )
    {
      if (!self()->isImmutable( QString::fromLatin1 ( "MainWindowSplitterSizes" ) ))
        self()->mMainWindowSplitterSizes = v;
    }

    /**
      Get Sizes of main splitter.
    */
    static
    QList<int> mainWindowSplitterSizes()
    {
      return self()->mMainWindowSplitterSizes;
    }

    /**
      Set Nick Name other users see.
    */
    static
    void setNickName( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1 ( "NickName" ) ))
        self()->mNickName = v;
    }

    /**
      Get Nick Name other users see.
    */
    static
    QString nickName()
    {
      return self()->mNickName;
    }

  protected:
    KobbySettings();
    friend class KobbySettingsHelper;


    // ui
    QList<int> mMainWindowGeometry;
    QList<int> mMainWindowSplitterSizes;

    // profile
    QString mNickName;

  private:
};

}

#endif

