// This file is generated by kconfig_compiler from kobbysettings.kcfg.
// All changes you do to this file will be lost.
#ifndef KOBBY_KOBBYSETTINGS_H
#define KOBBY_KOBBYSETTINGS_H

#include <kconfigskeleton.h>
#include <kdebug.h>

namespace Kobby {

class KobbySettings : public KConfigSkeleton
{
  public:

    static KobbySettings *self();
    ~KobbySettings();

    /**
      Set Main Window location and size.
    */
    static
    void setMainWindowGeometry( const QList<int> & v )
    {
      if (!self()->isImmutable( QString::fromLatin1 ( "MainWindowGeometry" ) ))
        self()->mMainWindowGeometry = v;
    }

    /**
      Get Main Window location and size.
    */
    static
    QList<int> mainWindowGeometry()
    {
      return self()->mMainWindowGeometry;
    }

    /**
      Set Sizes of main horizontal splitter.
    */
    static
    void setMainWindowHorizSplitterSizes( const QList<int> & v )
    {
      if (!self()->isImmutable( QString::fromLatin1 ( "MainWindowHorizSplitterSizes" ) ))
        self()->mMainWindowHorizSplitterSizes = v;
    }

    /**
      Get Sizes of main horizontal splitter.
    */
    static
    QList<int> mainWindowHorizSplitterSizes()
    {
      return self()->mMainWindowHorizSplitterSizes;
    }

    /**
      Set Nick Name other users see.
    */
    static
    void setNickName( const QString & v )
    {
      if (!self()->isImmutable( QString::fromLatin1 ( "NickName" ) ))
        self()->mNickName = v;
    }

    /**
      Get Nick Name other users see.
    */
    static
    QString nickName()
    {
      return self()->mNickName;
    }

    /**
      Set Color user appears as on server.
    */
    static
    void setUserColor( const QColor & v )
    {
      if (!self()->isImmutable( QString::fromLatin1 ( "UserColor" ) ))
        self()->mUserColor = v;
    }

    /**
      Get Color user appears as on server.
    */
    static
    QColor userColor()
    {
      return self()->mUserColor;
    }

  protected:
    KobbySettings();
    friend class KobbySettingsHelper;


    // ui
    QList<int> mMainWindowGeometry;
    QList<int> mMainWindowHorizSplitterSizes;

    // profile
    QString mNickName;
    QColor mUserColor;

  private:
};

}

#endif

