#ifndef KTECOLLABORATIVECOMMON_EXPORT_H
#define KTECOLLABORATIVECOMMON_EXPORT_H

#include <kdemacros.h>

#ifndef KTECOLLABORATIVECOMMON_EXPORT
# if defined(MAKE_KTECOLLABORATIVECOMMON_LIB)
   // We are building this library
#  define KTECOLLABORATIVECOMMON_EXPORT KDE_EXPORT
# else
   // We are using this library
#  define KTECOLLABORATIVECOMMON_EXPORT KDE_IMPORT
# endif
#endif

# ifndef KTECOLLABORATIVECOMMON_EXPORT_DEPRECATED
#  define KTECOLLABORATIVECOMMON_EXPORT_DEPRECATED KDE_DEPRECATED KTECOLLABORATIVECOMMON_EXPORT
# endif

#endif