set( CMAKE_ALLOW_LOOSE_LOOP_CONSTRUCTS true )

set( libinfinitymm_FOUND	false )
	
find_program( _LIBINFINITYMM_CONFIG_EXECUTABLE NAMES libinfinitymm-config )

if ( _LIBINFINITYMM_CONFIG_EXECUTABLE )
	exec_program( ${_LIBINFINITYMM_CONFIG_EXECUTABLE} ARGS --version OUTPUT_VARIABLE LIBINFINITYMM_VERSION )
	
	exec_program( ${_LIBINFINITYMM_CONFIG_EXECUTABLE} ARGS --libs OUTPUT_VARIABLE _LIBINFINITYMM_LIBS )
	
	exec_program( ${_LIBINFINITYMM_CONFIG_EXECUTABLE} ARGS --cflags OUTPUT_VARIABLE _LIBINFINITYMM_CFLAGS )
	
	if ( _LIBINFINITYMM_CFLAGS )
		string( REGEX REPLACE "(\r?\n)+$" " " _LIBINFINITYMM_CFLAGS  "${_LIBINFINITYMM_CFLAGS}" )
		string( REGEX REPLACE " *-I"      ";" LIBINFINITYMM_INCLUDES "${_LIBINFINITYMM_CFLAGS}" )
	endif()
	
endif()
